# 一、创建工程
### (1) 基本工程创建过程
参考 https://blog.csdn.net/Oskar_Lu/article/details/99136423 配置即可。 
使用.NET 对应的 Class Library 进行创建
![[attachments/Pasted image 20240318172143.png]]
参考文章配置即可
![[attachments/Pasted image 20240318164454.png]]
添加属性方法如下: 
![[attachments/Pasted image 20240318172615.png]]
编译完毕后， 进行Attach 即可(Attach时需要打开UG程序)
![[attachments/Pasted image 20240318173313.png]]
Edit Action 中添加对应的命令选项: 
![[attachments/Pasted image 20240318173847.png]]
在每一次修改程序之后， 使用Build -> Build Solution 即可, 注意不用 start (这样会启动NX程序)
![[attachments/Pasted image 20240318181206.png|800]]

```cs title:当运行程序时，只需将函数名字在里面加一个Main函数即可
using System;
using NXOpen;

namespace ClassLibraryTest
{
    public class Class1
    {
        public static void Main(string[] args)
        {
            NXOpen.Session session = NXOpen.Session.GetSession();
            NXOpen.Part workPart = session.Parts.Work;     // 获取当前工作部件
        }
    }
}
```

### (2) 录制宏命令的方法
录制宏是最有用的命令，可以复现建模过程中的命令执行;

录制宏选项如图: 首先在File > Preference > User Interface > Tools > Journal中找到相应的界面。
并设置录制语言和Format(UTF-8) 

![[attachments/Pasted image 20240318175443.png]]

![[attachments/Pasted image 20240318180311.png]]

草图创建: 在草图的创建中， 返回的 是NXOpen.Objects类型， 因此必须转换成NXOpen.Sketch类型才能进行索引;
```cs
NXOpen.NXObject nXObject2;
nXObject2 = sketchInPlaceBuilder1.Commit();
NXOpen.Sketch sketch1 = (NXOpen.Sketch)nXObject2;
```

https://docs.nxlog.co/integrate/dotnet.html 程序运行失败后， 使用Help  > Log File 获取
![[attachments/Pasted image 20240318192314.png]]

### (3) 调试输出文件的位置
调试输出的日志文件可以在   C:\Users\Parrot\AppData\Local\Temp   中找到, 
搜索.syslog文件即可。一般在最后面可以找到对应的Log信息;

![[attachments/Pasted image 20240318193947.png]]

E:\workpack\C#\NXdevelopment\ClassLibraryTest\ClassLibraryTest\Class1.cs:line 37 表明了错误的位置;

目前, 输出的文件可以在自定义路径 E:\NX12\TEMP 下找到; 

#### (4) 文档获取
由于网站不安全， 需要使用桌面上的 chorm -unsafe 进入文档
修改了属性设置 -Target ,  --ignore-certificate-errors 
会强制忽略网站 SSL 证书;

# 二、基本指令

首先我们以 rules 的创建方法说明 NXOpen 中的类继承关系:
CurveChain
![[attachments/Pasted image 20240318220040.png|1000]]

其中, C# 中进行调用控制台输出即为简单， 只要两行代码: 
```cs
using NXOpen.UF;

var uFSession = UFSession.GetUFSession();
uFSession.Ui.DisplayMessage("Cube Created Successfully", 1);
```

其中 NXOpen.ApparentChaningRule 等等都是 NXOpen.SelectionIntentRule 类, 并可以使用 workPart.ScRuleFactory.Create..... 进行创建

### (1) 草图创建和拉伸的代码
草图创建的示例代码如下:

```csharp fold title:草图创建代码 
using System;
using NXOpen;
using NXOpen.Features;
using NXOpen.GeometricUtilities;

namespace ClassLibraryTest
{
    public class Class1
    {
        public static void Main(string[] args)
        {
            NXOpen.Session session = NXOpen.Session.GetSession();
            NXOpen.Part workPart = session.Parts.Work;     // 获取当前工作部件

            Point3d point1 = new Point3d(0.0, 0.0, 0.0);
            Point3d point2 = new Point3d(0.0, 1.0, 0.0);
            Point3d point3 = new Point3d(1.0, 1.0, 0.0);
            Point3d point4 = new Point3d(1.0, 0.0, 0.0);

            
            var skt1_builder = workPart.Sketches.CreateSketchInPlaceBuilder2(null);
            Point origin_point = workPart.Points.CreatePoint(new Point3d(0.0, 0.0, 0.0));
            skt1_builder.SketchOrigin = origin_point;

            Direction Zdir = workPart.Directions.CreateDirection(origin_point, new Vector3d(0.0, 0.0, 1.0));
            skt1_builder.AxisReference = Zdir;
            var sketch1 = (Sketch)skt1_builder.Commit();
            sketch1.Activate(Sketch.ViewReorient.True);

            Line line1 = workPart.Curves.CreateLine(point1, point2);
            Line line2 = workPart.Curves.CreateLine(point2, point3);
            Line line3 = workPart.Curves.CreateLine(point3, point4);
            Line line4 = workPart.Curves.CreateLine(point4, point1);

            Line[] Lines = {line1, line2, line3, line4};
            foreach (Line line in Lines)
            {
                sketch1.AddGeometry(line, Sketch.InferConstraintsOption.InferNoConstraints);
            }
            sketch1.Update();
            sketch1.Deactivate(Sketch.ViewReorient.False, Sketch.UpdateLevel.Model);
        }
    }
}
```

拉伸需要使用CreateExtrudeBuilder, 同时需要指定截面， 拉伸方向和拉伸长度, 具体如下: 
说明: 下面的代码是在XY平面上创建了正方体并指定了拉伸方向为草图的正向;
```cs title:正方体创建代码
using System;
using NXOpen;
using NXOpen.Features;
using NXOpen.GeometricUtilities;

namespace ClassLibraryTest
{
    public class Class1
    {
        public static void Main(string[] args)
        {
            NXOpen.Session session = NXOpen.Session.GetSession();
            NXOpen.Part workPart = session.Parts.Work;     // 获取当前工作部件

            Point3d point1 = new Point3d(0.0, 0.0, 0.0);
            Point3d point2 = new Point3d(0.0, 1.0, 0.0);
            Point3d point3 = new Point3d(1.0, 1.0, 0.0);
            Point3d point4 = new Point3d(1.0, 0.0, 0.0);
            
            var skt1_builder = workPart.Sketches.CreateSketchInPlaceBuilder2(null);
            Point origin_point = workPart.Points.CreatePoint(new Point3d(0.0, 0.0, 0.0));
            skt1_builder.SketchOrigin = origin_point;
            
            // 草图创建部分代码;
            Direction Zdir = workPart.Directions.CreateDirection(origin_point, new Vector3d(0.0, 0.0, 1.0));
            skt1_builder.AxisReference = Zdir;
            var sketch1 = (Sketch)skt1_builder.Commit();
            skt1_builder.Destroy();
            sketch1.Activate(Sketch.ViewReorient.True);

            Line line1 = workPart.Curves.CreateLine(point1, point2);
            Line line2 = workPart.Curves.CreateLine(point2, point3);
            Line line3 = workPart.Curves.CreateLine(point3, point4);
            Line line4 = workPart.Curves.CreateLine(point4, point1);

            Line[] Lines = {line1, line2, line3, line4};
            foreach (Line line in Lines)
            {
                sketch1.AddGeometry(line, Sketch.InferConstraintsOption.InferNoConstraints);
            }
            sketch1.Update();
            sketch1.Deactivate(Sketch.ViewReorient.False, Sketch.UpdateLevel.Model);  // 关闭草图

            // 数组使用 new 的初始化方法
            Section section1 = workPart.Sections.CreateSection();   // 使用默认的创建截面函数
            SelectionIntentRule[] rules1 = new NXOpen.SelectionIntentRule[1];
            
            // 将草图的线指定为截面线
            Feature[] features1 = new Feature[1];
            features1[0] = sketch1.Feature;         // 获取草图特征
            rules1[0] = workPart.ScRuleFactory.CreateRuleCurveFeatureChain(features1,line1,null,false,0.01);
            // 注意:CurveChainRule等等都是继承类，初始化此对象时, 

            // 注意: 这里直接使用 null 来指定 features (实际上是NXOpen.Features.Null)
            ExtrudeBuilder extrudeBuilder1 = workPart.Features.CreateExtrudeBuilder(null);
            extrudeBuilder1.Section = section1;
            // line1 是选中的部分, 而rules1指定了全选sketch中的内容
            section1.AddToSection(rules1, line1, null, null, new Point3d(0.0, 0.0, 0.0), Section.Mode.Create);
            
            // 指定拉伸方向, sense 指定向量的正向和反向, 并指定拉伸长度
            Direction dir2 = workPart.Directions.CreateDirection(sketch1, Sense.Forward, SmartObject.UpdateOption.WithinModeling);
            extrudeBuilder1.Direction = dir2;
            extrudeBuilder1.Limits.StartExtend.Value.RightHandSide = "0";
            extrudeBuilder1.Limits.EndExtend.Value.RightHandSide = "1";

            var cube_object = extrudeBuilder1.Commit();
            // extrudeBuilder1.Destroy();
        }
    }
}
```

### (2) 撤销标签,  标签寻址和删除特征
首先，删除特征等需要了解 UndoMarkID 的用法, <b><mark style="background: transparent; color: blue">UndoMarkID 实际上是 "撤销标志位"的意思, 一般在 Session.UpdateManager.DoUpdate 方法中都要调用来便于撤销操作</mark></b>;
```cs title:设置UndoMarkID实际上只需要一句代码
var markDelete = session.SetUndoMark(Session.MarkVisibility.Invisible, "Hide Sketch"); 
// 其中Visible 设置是否用户是可见的， 即是否允许用户的撤销操作
```
在界面中三次点击可以得到如图撤销列表, 其中包含了设置的UndoMark; 
![[attachments/Pasted image 20240320141253.png|600]]

需要说明的是， 每一部分的 Name 应当是唯一的， 从而用以作为唯一标识符来进行

```cs title:删除一个方块的代码
TaggedObject[] obj1 = new TaggedObject[1];
obj1[0] = (NXOpen.Features.Extrude) cube1;

session.UpdateManager.AddObjectsToDeleteList(obj1);
// 创建标志点, 可以使用 UndoToMarkWithStatus回滚到之前的状态; -> 其中Visible 设置对用户可见
var markDelete = session.SetUndoMark(Session.MarkVisibility.Visible, "Delete");
session.UpdateManager.DoUpdate(markDelete);
session.DeleteUndoMark(markDelete,"Delete");  // 删除UndoMark, 第一个参数是对应的变量，第二个给定字符串, 一般是标记点
```

如果是想为一个部分设置名称，可以调用SetName方法, 之后可以通过在Session 的WorkPart中遍历获取对应的方法; <mark style="background: transparent; color: red">以下代码演示了设置名称， 和遍历草图寻找名称然后进行删除操作</mark>;

> [!caution] 注意
> 对于草图， 也可以直接使用workPart.Sketches.FindObject 会导致找不到对象, 

```cs
sketch1.SetName("TestSketch");

foreach (Sketch sketch in session.Parts.Work.Sketches)
{
	if (sketch.Name == "TESTSKETCH")
	{
		// 删除名字是TESTSKETCH的草图
		Delete_object(session, sketch);
	}
}
```

### (3) 创建平面的方法

```cs title:一般平面创建方法 
workPart.Planes.CreatePlane(new Point3d(0.0, 0.0, 0.0), new Vector3d(1.0, 0.0, 0.0), SmartObject.UpdateOption.WithinModeling);
// 这个一般是正确的， 但是如果平面浮空， 则创建草图时会有Internal Error, 因此可以使用参考平面代替
```
参考平面是通过先设定一系列值， 然后最后使用 Evaluate 进行创建的。
```cs title:参考平面创建
// dataum plane creation
DatumPlaneBuilder datumPlaneBuilder1;
datumPlaneBuilder1 = workPart.Features.CreateDatumPlaneBuilder(null);

Plane plane2 = datumPlaneBuilder1.GetPlane();
plane2.SetMethod(PlaneTypes.MethodType.Distance);
NXObject[] geom1 = new NXObject[1] { coor_ref.Plane_ref.XZplane };  //设置参考对象(随便一个平面)
plane2.SetGeometry(geom1);   // 赋值到Geometry属性中; 
plane2.SetFlip(false);
plane2.SetReverseSide(false);
plane2.Expression.RightHandSide = TJParameter.flangeThickness.ToString();
plane2.SetAlternate(PlaneTypes.AlternateType.One);  // 一般直接加上即可， 不管太多
plane2.Evaluate();  // evalue the plane (replace the plane)

// create points on reference plane 2 -> 在参考平面上创建草图
var sketchbuilder2 = workPart.Sketches.CreateSketchInPlaceBuilder2(null);  // null for brand new sketch
sketchbuilder2.SketchOrigin = coor_ref.origin;
sketchbuilder2.AxisReference = coor_ref.Direction_ref.x_Direction;
sketchbuilder2.PlaneReference = plane2;
Sketch sketch2 = (Sketch)sketchbuilder2.Commit();
sketchbuilder2.Destroy();
```

### (4) 在平面上钻孔的代码
可以通过
```cs
NXOpen.Session.BeginTaskEnvironment() 
```
来进入一个子工作环境， 例如添加孔时，绘制草图等等

我们实际指定孔时,  最终将点添加到孔的操作调用的函数根据类型而指定， 


```cs
HolePackageBuilder holebuilder1 =  workPart.Features.CreateHolePackageBuilder(null); // 创建孔

holePackageBuilder3.HolePosition.AddToSection(rules, null, null, null, helpPoint, NXOpen.Section.Mode.Create);
```
通过HolePosition设置多个孔的位置, 实际上返回的是一个 Section 对象, 而可以通过AddToSection向其中添加截面规则; 
注意设置Body对象不能直接强制类型转换， 否则会出现 `Unable to cast object of type 'NXOpen.Features.Extrude' to type 'NXOpen.Body'.` 实际上， 应该使用 Extrude 类型的GetBodies方法;

钻孔指定直径和深度时， **必须事先指定钻孔类型，然后再指定对应类型孔的高度和直径** 
一般我们指定基本的孔为 GeneralHole, 而对应设置直径的方法为 `holebuilderpackage1.GeneralSimpleHoleDiameter` 和 `holebuilderpackage1.GeneralSimpleHoleDepth`,  如果是钻孔的话， 则可能是GeneralDrillHoleDiameter和GeneralDrillHoleDepth等等

```cs fold title:孔组的基本添加操作代码(首先需要三个点)
// --------- Create Hole Features ----------------- 
var markID4 = theSession.SetUndoMark(Session.MarkVisibility.Visible, "Create Holes");

HolePackageBuilder holebuilder1 =  workPart.Features.CreateHolePackageBuilder(null); // new hole feature 

holebuilder1.StartHoleData.BooleanOperation.SetTargetBodies(new Body[]{ null });
holebuilder1.MiddleHoleData.BooleanOperation.SetTargetBodies(new Body[] { null });
// Boolean Type is from GeometricUtilitiess (Optional)
holebuilder1.StartHoleData.BooleanOperation.Type = BooleanOperation.BooleanType.Subtract;

Body[] body1 = new Body[] { null };
holebuilder1.BooleanOperation.SetTargetBodies(body1);
// 三个部分, 这三个部分可以不加(都是默认)
holebuilder1.StartHoleData.BooleanOperation.SetTargetBodies(new Body[] { null });
holebuilder1.MiddleHoleData.BooleanOperation.SetTargetBodies(new Body[] { null });
holebuilder1.EndHoleData.BooleanOperation.SetTargetBodies(new Body[] { null });
holebuilder1.HolePosition.SetAllowedEntityTypes(NXOpen.Section.AllowTypes.OnlyPoints);
// 设置 Tolerance 部分
holebuilder1.Tolerance = 0.01;
holebuilder1.HolePosition.DistanceTolerance = 0.01;
holebuilder1.HolePosition.ChainingTolerance = 0.0096;

/* 设置Boolean Operation 的 TargetBody 属性才是设置对应的布尔对象 */
Body[] flange1_body = flange1.GetBodies();   // 直接从flange1 获取bodies对象(注意必须是Extrude类型)
holebuilder1.BooleanOperation.SetTargetBodies(flange1_body);
// ******* 设置孔的直径和高度 (这一块是重点) *******
holebuilderpackage1.Type = HolePackageBuilder.Types.GeneralHole;  // 构造类型
holebuilderpackage1.GeneralSimpleHoleDiameter.RightHandSide = TJParameter.flangeHoleDiameter.ToString();
holebuilderpackage1.GeneralSimpleHoleDepth.RightHandSide = TJParameter.flangeThickness.ToString();
// 用CurveDumbRule将所有的点添加到点集中;
Point[] points1 = new Point[] { workPart.Points.CreatePoint(point5), 
								workPart.Points.CreatePoint(point6),
								workPart.Points.CreatePoint(point7)};
CurveDumbRule[] rules2 = new CurveDumbRule[] { workPart.ScRuleFactory.CreateRuleCurveDumbFromPoints(points1) };
holebuilder1.HolePosition.AddToSection(rules2, null, null, null, new Point3d(0.0,0.0,0.0), Section.Mode.Create);

var holepackage1 = (HolePackage)holebuilder1.Commit();
holepackage1.SetName("Flange Holes");
holebuilder1.Destroy();
```

![[attachments/Pasted image 20240320134208.png|700]]

### (5) 设置对象的隐藏和显示
方法是创建一个DisplayableObject,  
```cs
// ------------- Hide The Sketches ------------- 
theSession.SetUndoMark(Session.MarkVisibility.Visible, "Hide Sketch");
DisplayableObject[] objects1 = new DisplayableObject[2];
objects1[0] = sketch1;
objects1[1] = sketch2;
theSession.DisplayManager.BlankObjects(objects1);  // 取消其中这些的显示
// theSession.DisplayManager.ShowObjects -> 显示对应的对象
```

### (6) 基本布尔运算
在布尔运算中需要两个Body[] 数组, 而包括目标体(原体)， 工具体(第二选择);
布尔类型通过 `booleanBuilder1.Operation` 指定
目标体通过 `booleanBuilder1.Targets.Add` 指定 
而工具体通过 `scCollector1` 指定，其中需要先创建对象， 置换rules, 再
```cs
// ------------ Boolean Operation --------------- 
theSession.SetUndoMark(Session.MarkVisibility.Visible, "Do Combination");
BooleanBuilder booleanBuilder1 = workPart.Features.CreateBooleanBuilder(null);
booleanBuilder1.Operation = Feature.BooleanType.Unite;

TaggedObject[] targets1 = targetbodies1;
booleanBuilder1.Targets.Add(targetbodies1[0]);  // 通过Targets.Add 来添加目标

// 创建规则, include sheet bodies 指定了是否包含草图
BodyDumbRule bodyDumbRule1 = workPart.ScRuleFactory.CreateRuleBodyDumb(toolbodies1, false);

var scCollector1 = workPart.ScCollectors.CreateCollector(); // 创建 Collectpr 
scCollector1.ReplaceRules(new SelectionIntentRule[] { bodyDumbRule1 }, false);  // 替换rules (false 会更新收集器)
booleanBuilder1.ToolBodyCollector = scCollector1; // 将 scCollector1 赋值给 booleanBuilder
// booleanBuilder1.BooleanRegionSelect.AssignTargets(targets1);

NXObject res_obj = booleanBuilder1.Commit();
booleanBuilder1.Destroy();
```

