# 一、调试窗口输出方法
参考官方文档， 可以看到UFSession的调用方法:
![[attachments/Pasted image 20240316210935.png]]
即使用GetUFSession来返回UF Session 对象;
```py
import NXOpen.UF
def main():
	NXOpen.UF.UFSession.GetUFSession().Ui.DisplayMessage("Hello World!", 1)
if __name__ == '__main__':
	main()
```

To create a new instance of this class, use `NXOpen.SectionCollection.CreateSection()`
在UG NX中的Session对象实际上是如图的结构部分 : 
![[attachments/Pasted image 20240316212236.png]]

```python
import NXOpen

def main(): 
    listing_window = NXOpen.Session.GetSession().ListingWindow
    
    listing_window.Open()
    listing_window.WriteFullline("Hello world!")
    listing_window.Close()

if __name__ == '__main__':
    main()
```

在Session中除了默认的GetSession以外, 还有Parts()类型,   因此可以利用.Parts()来获取其下的部件。
![[attachments/Pasted image 20240316212635.png]]
而对于PartCollection类型， 实际上结构图如下:
![[attachments/Pasted image 20240316212914.png]]
实际索引关系如图所示
![[Excalidraw/入门与常用函数 2024-03-18 09.49.26|700]]
Work 实际上就是 .prt 部件的部分, 返回值是工作文件(即.prt工作对象) , 而其中对应的workcomponent 就是整个场景中的工作部件。 
![[attachments/Pasted image 20240316213246.png|900]]

> [!caution] 说明
> 我们在工作中设置的work_part变量， 实际上是NXOpen::Part类型
> 例如work_part.Features, 实际上是从 NXOpen.BasePart 中继承得到的(参考[NXOpen Python Reference](https://docs.plm.automation.siemens.com/data_services/resources/nx/1899/nx_api/custom/en_US/nxopen_python_ref/a07944.html));
> 对应的Features获取到的是featureCollection对象

NXOpen.BasePart的Feature 图像如下: 
![[attachments/Pasted image 20240318102507.png]]


# 二、创建基础的点和线的方法
### (1) 创建点线
线的创建实际上是在 NXOpen.**CurveCollection** Class Reference 中的。

```python title:创建线的示例代码
import NXOpen
import NXOpen.UF
from NXOpen import Point3d,Vector3d

def create_points(session, side_length):
    work_part = session.Parts.Work
    features = work_part.Features
    
    # 创建点 -> Point3d实际上不会生成实例对象
    point1 = NXOpen.Point3d(0.0, 0.0, 0.0)
    point2 = NXOpen.Point3d(side_length, 0.0, 0.0)
    point3 = NXOpen.Point3d(side_length, side_length, 0.0)
    point4 = NXOpen.Point3d(0.0, side_length, 0.0)

    # 创建线 -> 会在模型中生成对象
    line1 = work_part.Curves.CreateLine(point1, point2)
    line2 = work_part.Curves.CreateLine(point2, point3)
    line3 = work_part.Curves.CreateLine(point3, point4)
    line4 = work_part.Curves.CreateLine(point4, point1)

if __name__ == "__main__":
	# 获取当前的NX session
	session = NXOpen.Session.GetSession()
	# 调用函数创建正方体
	create_points()
```

上面使用了当前的Session, 并使用session.Parts.Work获取了当前的工作部件prt; 同时如果想创建新的工作部件， 可以使用下面的代码: 
```python
# 创建新的工作部件
workPart = theSession.Parts.NewDisplay("sketch", NXOpen.Part.Units.Millimeters)
```

### (2) 创建草图
根据文档描述, 在 NXOpen.**SketchCollection** Class Reference   中， 提供了 CreateSketchInDraftingBuilder 方法和 CreateSketchInPlaceBuilder2 方法, 用于构建草图;
![[attachments/Pasted image 20240316231245.png]]

> [!caution] 说明
> 需要说明的是, 根据文档 NXOpen.SketchCollection.CreateNewSketchinPlaceBuilder方法有描述: 
Created in NX7.5.0 , Deprecated in NX11.0.0. Use [NXOpen::SketchCollection::CreateSketchInPlaceBuilder2](https://docs.plm.automation.siemens.com/data_services/resources/nx/1899/nx_api/custom/en_US/nxopen_python_ref/a10891.html#a964aefde26b3ff58e0b68fd3fab90acc) instead.
即已经在11.0被移除。

 调用代码示例如下:
```python
builder = work_part.Sketches.CreateSketchInPlaceBuilder2(NXOpen.Sketch.Null)  
# 注意文档中的Null指的是对应的类下的Null对象, 即参数为Null时, 新建一个
sketch1 = builder.Commit()
builder.Destroy()
```
这样我们就新建了一个草图, 
![[attachments/Pasted image 20240317005103.png]]

而在草图中添加线段， 则需要 NXOpen.Sketch.AddGeometry 方法, 解释如下图:
![[attachments/Pasted image 20240317010914.png]]

```python title:输出当前所有平面名字
listing_window = session.ListingWindow    
listing_window.Open()
for plane in work_part.Planes:
	listing_window.WriteFullline(plane.Name)
listing_window.Close()
```

```python title:完整的创建草图和添加几何体示例:
# 创建草图
builder = work_part.Sketches.CreateSketchInPlaceBuilder2(NXOpen.Sketch.Null)
sketch1 = builder.Commit()
builder.Destroy()  # 关闭创建器(实际上是创建窗口)

sketch1.Activate(NXOpen.Sketch.ViewReorient.TrueValue) # 激活草图同时 re-orient view to sketch
# 创建点
point1 = NXOpen.Point3d(0.0, 0.0, 0.0)
point2 = NXOpen.Point3d(side_length, 0.0, 0.0)
point3 = NXOpen.Point3d(side_length, side_length, 0.0)
point4 = NXOpen.Point3d(0.0, side_length, 0.0)

# 创建线
line1 = work_part.Curves.CreateLine(point1, point2)
line2 = work_part.Curves.CreateLine(point2, point3)
line3 = work_part.Curves.CreateLine(point3, point4)
line4 = work_part.Curves.CreateLine(point4, point1)

sketch1.AddGeometry(line1, NXOpen.Sketch.InferConstraintsOption.InferNoConstraints)
sketch1.AddGeometry(line2, NXOpen.Sketch.InferConstraintsOption.InferNoConstraints)
sketch1.AddGeometry(line3, NXOpen.Sketch.InferConstraintsOption.InferNoConstraints)
sketch1.AddGeometry(line4, NXOpen.Sketch.InferConstraintsOption.InferNoConstraints)
sketch1.Update()  # 绘制完毕之后,更新草图
sketch1.Deactivate(NXOpen.Sketch.ViewReorient.FalseValue, NXOpen.Sketch.UpdateLevel.Model) 
# 关闭激活草图
```

结果如下图所示: 
![[attachments/Pasted image 20240317021953.png|700]]

由于 NX.part.sketches 返回的是一个 SketchCollection 对象,  
![[attachments/Pasted image 20240318092235.png]]
### (3) 创建拉伸对象
搜索 Extrude 来创建相应的拉伸, 而创建拉伸实例需要使用 NXOpen.Features.FeatureCollection.CreateExtrudeBuilder

> [!hint] 说明
> 这个拉伸对象是基于CreateExtrudeBuilder 进行创建的
> 如果试图使用NXOpen.Features.ExtrudeBuilder, 则会报错 "NXOpen.Features has no attribute Extrude Builder", 这个是因为没有引用 NXOpen.Features, 因此我们需要通过import 来引用这个包， 然后才能进行使用。

比较容易误用代码部分如下:(下面的代码实际上可以通过from NXOpen.Features import ExtrudeBuilder解决)
![[attachments/Pasted image 20240318104557.png]]
参考NXOpen.Features.FeatureCollection.CreateExtrudeBuilder方法, 里面需要一个Extrude对象， 这个对象需要NX.Features.ExtrudeBuilder来建立。
![[attachments/Pasted image 20240318104843.png]]

对于Public Member Functions， **有些特征是只读的， 而有些特征是可以设置的**，这些可以查阅文档, 其中Getter是获取, Setter是设置, 而**对于可以设置的部分， 可以在初始化时， 直接传入参数,  示例如下**
```python title:初始化时传输参数的办法
ext1 = NXOpen.Features.ExtrudeBuilder(Direction = NXOpen.Vector3d(0.0, 0.0, side_length)) # this method return NXOpen.Features.Extrude class
```

根据文档,  To create a new instance of this class, use <b><mark style="background: transparent; color: blue">NXOpen::Features::FeatureCollection::CreateExtrudeBuilder</mark></b> , 但是这个函数需要传入(NXOpen::Features::Feature )(NXOpen::Features::Extrude)类型的参数作为拉伸的依据; 

此时, 如果我们使用默认， 则传入Features.Null即可
```python
feature = NXOpen.Features.Feature() # FeatureCollection Object 
blockFeatureBuilder = work_part.Features.CreateBlockFeatureBuilder(feature.Null)  # 表示以空初始化物体
```
> [!NOTE] 说明
> NXOpen::Features::FeatureCollection 是一个方法很多的类, 即处理的基本所有步骤都在这一类中。



**NXOpen.SectionCollection.CreateSection方法**来进行创建截面。其中这个方法可以设置tolerance, 但是一般使用下面的两种方法: 
![[attachments/Pasted image 20240318140317.png]]
第二种是传入曲线参数的: 
![[attachments/Pasted image 20240318140703.png]]

```python title:update_method的说明
update_method = NXOpen.SmartObject.UpdateOption.WithinModeling

direction = work_part.Directions.CreateDirection(NXOpen.Point3d(0.0,0.0,0.0),NXOpen.Vector3d(0.0,0.0,1.0), update_method) # DirectionCollection Object -> 一般第三个参数直接填入即可

ext1 = NXOpen.Features.ExtrudeBuilder();
```

## NXOpen.Feature的初始化为Null方式

python的代码部分和C# 很像, 但是不用初始化对象

> [!caution] 注意
> 如果提示 "NXOpen HaveNoAttributes GeometricUtilities", 是没有import 的问题， 所以一定要加上 import 部分

```python title:
import NXOpen.GeometricUtilities   #  如果不import会报错

feature = NXOpen.Features.Feature() # FeatureCollection Object 
blockFeatureBuilder = work_part.Features.CreateBlockFeatureBuilder(feature.Null)  # 表示以空初始化物体
```

## 使用BlockBuilder 创建长方体

```python
import NXOpen
import NXOpen.UF
import NXOpen.Features
import NXOpen.GeometricUtilities

from NXOpen import Point3d,Vector3d
def create_cube(session, side_length):
	point1 = NXOpen.Point3d(0.0, 0.0, 0.0)
    feature = NXOpen.Features.Feature()  # FeatureCollection Object
    blockFeatureBuilder = work_part.Features.CreateBlockFeatureBuilder(feature.Null)
    
    
    blockFeatureBuilder.BooleanOption.Type = NXOpen.GeometricUtilities.BooleanOperation.BooleanType.Create
    blockFeatureBuilder.Type = NXOpen.Features.BlockFeatureBuilder.Types.OriginAndEdgeLengths
    
    originPoint = work_part.Points.CreatePoint(point1)  # NXOpen.Point originPoint 
    # 设置坐标
    blockFeatureBuilder.OriginPoint = originPoint
    blockFeatureBuilder.SetOriginAndLengths(point1, "100","200", "500")
    
    # 创建正方体
    blockFeatureBuilder.CommitFeature()
    blockFeatureBuilder.Destroy()
```

另外也可以使用
```cs
NXOpen.Features.Extrude extrude1 = (NXOpen.Features.Extrude)workPart.Features.FindObject("EXTRUDE(2)");
```