# 坐标参考类
直接将类复制粘贴到代码中, 主函数调用创建对象:
```cs
private static Coordinate_References coor_ref; // Main外部

coor_ref = new Coordinate_References(workPart); /* 初始化 原点和 MyDirections 对象并初始化三个方向向量 */
```
然后直接调用获取即可
```cs fold title:坐标参考类
public class Coordinate_References
{
	public struct CoorDirections
	{
		public Direction x_Direction { get; set; }
		public Direction y_Direction { get; set; }
		public Direction z_Direction { get; set; }
	};

	public struct CoorPlanes
	{
		public Plane YZplane { get; set; }
		public Plane XZplane { get; set; }
		public Plane XYplane { get; set; }
	};
	private static CoorDirections directions;
	private static CoorPlanes planes;
	private static Point originPoint;
	public CoorDirections Direction_ref
	{
		get{ return directions;}
	}
	public CoorPlanes Plane_ref
	{
		get{ return planes;}
	}
	public Point origin
	{
		get{ return originPoint;}
	}
	// 初始化函数
	public Coordinate_References(Part workPart)
	{
		// 注意: originPoint, directions和planes 都是static 对象，不需要new初始化
		originPoint = workPart.Points.CreatePoint(new Point3d(0.0, 0.0, 0.0));
		directions.x_Direction = workPart.Directions.CreateDirection(originPoint, new Vector3d(1.0, 0.0, 0.0));
		directions.y_Direction = workPart.Directions.CreateDirection(originPoint, new Vector3d(0.0, 1.0, 0.0));
		directions.z_Direction = workPart.Directions.CreateDirection(originPoint, new Vector3d(0.0, 0.0, 1.0));

		planes.XYplane = workPart.Planes.CreatePlane(new Point3d(0.0, 0.0, 0.0), new Vector3d(1.0, 0.0, 0.0), SmartObject.UpdateOption.WithinModeling);
		planes.XZplane = workPart.Planes.CreatePlane(new Point3d(0.0, 0.0, 0.0), new Vector3d(0.0, 1.0, 0.0), SmartObject.UpdateOption.WithinModeling);
		planes.YZplane = workPart.Planes.CreatePlane(new Point3d(0.0, 0.0, 0.0), new Vector3d(0.0, 0.0, 1.0), SmartObject.UpdateOption.WithinModeling);
	}
}
```


# 直接从点组创建草图

```cs
/// <summary>
/// General Skecth Create Function
/// </summary>
/// <param name="theSession">current Session</param>
/// <param name="points"> Must be given by sequence </param>
/// <param name="line_ref">use the last line as the reference line for section</param>
/// <returns></returns>
static Sketch Create_Sketch(Session theSession, Point3d[] points, Point sketchOrigin, Direction axisReference ,Plane sketchPlane, string sketchName, out Line line_ref)
{
	var workPart = theSession.Parts.Work;
	theSession.SetUndoMark(Session.MarkVisibility.Visible, "Create " + sketchName);

	var sketchBuilder = workPart.Sketches.CreateSketchInPlaceBuilder2(null);
	sketchBuilder.SketchOrigin = sketchOrigin;
	sketchBuilder.AxisReference = axisReference;
	sketchBuilder.PlaneReference = sketchPlane;
	
	var sketch1 = (Sketch)sketchBuilder.Commit();
	sketch1.SetName(sketchName);
	sketchBuilder.Destroy();

	sketch1.Activate(Sketch.ViewReorient.True);
	for (int i = 0; i < points.Length - 1; i++)
	{
		Line line = workPart.Curves.CreateLine(points[i], points[i + 1]);
		sketch1.AddGeometry(line);
	}
	Line endline = workPart.Curves.CreateLine(points[points.Length - 1], points[0]);
	line_ref = endline;
	sketch1.AddGeometry(endline);
	sketch1.Update();
	sketch1.Deactivate(Sketch.ViewReorient.False, Sketch.UpdateLevel.Model);
	return sketch1;
}
```

# 从草图创建拉伸

```cs
/// <summary>
/// General Extrude from Sketch plane by the reference line
/// </summary>
static Extrude Extrude_From_Sketch(Session theSession, Sketch sketch, Line line_ref, Direction direction, float startValue, float endValue,string extrudeName)
{
	var workPart = theSession.Parts.Work;
	// ------------- extrude Operation ---------------
	theSession.SetUndoMark(Session.MarkVisibility.Visible, "Create " + extrudeName);
	Section section = workPart.Sections.CreateSection();
	Feature[] features = new Feature[] { sketch.Feature };
	CurveFeatureChainRule[] rules = new CurveFeatureChainRule[] { workPart.ScRuleFactory.CreateRuleCurveFeatureChain(features,line_ref, null, false, 0.01)};

	section.AddToSection(rules, line_ref, null, null, new Point3d(0.0,0.0,0.0), Section.Mode.Create);

	var extrudeBuilder = workPart.Features.CreateExtrudeBuilder(null);
	extrudeBuilder.Section = section;
	extrudeBuilder.Direction = direction;
	extrudeBuilder.Limits.StartExtend.Value.RightHandSide = startValue.ToString();
	extrudeBuilder.Limits.EndExtend.Value.RightHandSide = endValue.ToString();
	var ext_obj = (Extrude) extrudeBuilder.Commit();
	extrudeBuilder.Destroy();
	ext_obj.SetName(extrudeName);
	return ext_obj;
}
```

# 简单布尔运算

简单布尔运算函数如下: 

```cs
/// <summary>
/// General Boolean Function
/// </summary>
/// <param name="theSession"></param>
/// <param name="targetbody"></param>
/// <param name="toolbodies"></param>
/// <param name="booleanType"></param>
/// <param name="objname"></param>
/// <returns></returns>
static BooleanFeature Execute_Boolean(Session theSession, Body[] targetbody, Body[] toolbodies, Feature.BooleanType booleanType, string objname)
{
	var workPart = theSession.Parts.Work;
	// ------------ Boolean Operation --------------- 
	theSession.SetUndoMark(Session.MarkVisibility.Visible, "Do Boolean " + objname);
	BooleanBuilder booleanBuilder1 = workPart.Features.CreateBooleanBuilder(null);
	booleanBuilder1.Operation = booleanType;

	TaggedObject[] targets1 = targetbody;
	booleanBuilder1.Targets.Add(targetbody[0]);  // 通过Targets.Add 来添加目标

	// 创建规则, include sheet bodies 指定了是否包含草图
	BodyDumbRule bodyDumbRule1 = workPart.ScRuleFactory.CreateRuleBodyDumb(toolbodies, false);

	var scCollector1 = workPart.ScCollectors.CreateCollector(); // 创建 Collectpr 
	scCollector1.ReplaceRules(new SelectionIntentRule[] { bodyDumbRule1 }, false);  // 替换rules (false 会更新收集器)
	booleanBuilder1.ToolBodyCollector = scCollector1; // 将 scCollector1 赋值给 booleanBuilder
	// booleanBuilder1.BooleanRegionSelect.AssignTargets(targets1);

	BooleanFeature res_obj = (BooleanFeature)booleanBuilder1.Commit();
	res_obj.SetName(objname);
	booleanBuilder1.Destroy();
	return res_obj;
}
```

