# 一、创建工程
### (1) 基本工程创建过程
参考 https://blog.csdn.net/Oskar_Lu/article/details/99136423 配置即可。 
使用.NET 对应的 Class Library 进行创建
![[attachments/Pasted image 20240318172143.png]]
参考文章配置即可
![[attachments/Pasted image 20240318164454.png]]
添加属性方法如下: 
![[attachments/Pasted image 20240318172615.png]]
编译完毕后， 进行Attach 即可(Attach时需要打开UG程序)
![[attachments/Pasted image 20240318173313.png]]
Edit Action 中添加对应的命令选项: 
![[attachments/Pasted image 20240318173847.png]]

在每一次修改程序之后， 使用Build -> Build Solution 即可, 注意不用 start (这样会启动NX程序)
![[attachments/Pasted image 20240318181206.png]]

```cs title:当运行程序时，只需将函数名字在里面加一个Main函数即可
using System;
using NXOpen;

namespace ClassLibraryTest
{
    public class Class1
    {
        public static void Main(string[] args)
        {
            NXOpen.Session session = NXOpen.Session.GetSession();
            NXOpen.Part workPart = session.Parts.Work;     // 获取当前工作部件
        }
    }
}
```

### (2) 录制宏命令的方法
录制宏是最有用的命令，可以复现建模过程中的命令执行;

录制宏选项如图: 首先在File > Preference > User Interface > Tools > Journal中找到相应的界面。
并设置录制语言和Format(UTF-8) 

![[attachments/Pasted image 20240318175443.png]]

![[attachments/Pasted image 20240318180311.png]]

草图创建: 在草图的创建中， 返回的 是NXOpen.Objects类型， 因此必须转换成NXOpen.Sketch类型才能进行索引;
```cs
NXOpen.NXObject nXObject2;
nXObject2 = sketchInPlaceBuilder1.Commit();
NXOpen.Sketch sketch1 = (NXOpen.Sketch)nXObject2;
```

https://docs.nxlog.co/integrate/dotnet.html 程序运行失败后， 使用Help  > Log File 获取
![[attachments/Pasted image 20240318192314.png]]

### (3) 调试输出文件的位置
调试输出的日志文件可以在   C:\Users\Parrot\AppData\Local\Temp   中找到, 
搜索.syslog文件即可。一般在最后面可以找到对应的Log信息;

![[attachments/Pasted image 20240318193947.png]]

E:\workpack\C#\NXdevelopment\ClassLibraryTest\ClassLibraryTest\Class1.cs:line 37 表明了错误的位置;

目前, 输出的文件可以在自定义路径 E:\NX12\TEMP 下找到; 

# 二、基本指令

首先我们以 rules 的创建方法说明 NXOpen 中的类继承关系:
CurveChain
![[attachments/Pasted image 20240318220040.png|1000]]

其中, C# 中进行调用控制台输出即为简单， 只要两行代码: 
```cs
using NXOpen.UF;

var uFSession = UFSession.GetUFSession();
uFSession.Ui.DisplayMessage("Cube Created Successfully", 1);
```

其中 NXOpen.ApparentChaningRule 等等都是 NXOpen.SelectionIntentRule 类, 并可以使用 workPart.ScRuleFactory.Create..... 进行创建

### (1) 草图创建和拉伸的代码
草图创建的示例代码如下:

```csharp fold title:草图创建代码 
using System;
using NXOpen;
using NXOpen.Features;
using NXOpen.GeometricUtilities;

namespace ClassLibraryTest
{
    public class Class1
    {
        public static void Main(string[] args)
        {
            NXOpen.Session session = NXOpen.Session.GetSession();
            NXOpen.Part workPart = session.Parts.Work;     // 获取当前工作部件

            Point3d point1 = new Point3d(0.0, 0.0, 0.0);
            Point3d point2 = new Point3d(0.0, 1.0, 0.0);
            Point3d point3 = new Point3d(1.0, 1.0, 0.0);
            Point3d point4 = new Point3d(1.0, 0.0, 0.0);

            
            var skt1_builder = workPart.Sketches.CreateSketchInPlaceBuilder2(null);
            Point origin_point = workPart.Points.CreatePoint(new Point3d(0.0, 0.0, 0.0));
            skt1_builder.SketchOrigin = origin_point;

            Direction Zdir = workPart.Directions.CreateDirection(origin_point, new Vector3d(0.0, 0.0, 1.0));
            skt1_builder.AxisReference = Zdir;
            var sketch1 = (Sketch)skt1_builder.Commit();
            sketch1.Activate(Sketch.ViewReorient.True);

            Line line1 = workPart.Curves.CreateLine(point1, point2);
            Line line2 = workPart.Curves.CreateLine(point2, point3);
            Line line3 = workPart.Curves.CreateLine(point3, point4);
            Line line4 = workPart.Curves.CreateLine(point4, point1);

            Line[] Lines = {line1, line2, line3, line4};
            foreach (Line line in Lines)
            {
                sketch1.AddGeometry(line, Sketch.InferConstraintsOption.InferNoConstraints);
            }
            sketch1.Update();
            sketch1.Deactivate(Sketch.ViewReorient.False, Sketch.UpdateLevel.Model);
        }
    }
}
```

拉伸需要使用CreateExtrudeBuilder, 同时需要指定截面， 拉伸方向和拉伸长度, 具体如下: 
说明: 下面的代码是在XY平面上创建了正方体并指定了拉伸方向为草图的正向;
```cs title:正方体创建代码
using System;
using NXOpen;
using NXOpen.Features;
using NXOpen.GeometricUtilities;

namespace ClassLibraryTest
{
    public class Class1
    {
        public static void Main(string[] args)
        {
            NXOpen.Session session = NXOpen.Session.GetSession();
            NXOpen.Part workPart = session.Parts.Work;     // 获取当前工作部件

            Point3d point1 = new Point3d(0.0, 0.0, 0.0);
            Point3d point2 = new Point3d(0.0, 1.0, 0.0);
            Point3d point3 = new Point3d(1.0, 1.0, 0.0);
            Point3d point4 = new Point3d(1.0, 0.0, 0.0);
            
            var skt1_builder = workPart.Sketches.CreateSketchInPlaceBuilder2(null);
            Point origin_point = workPart.Points.CreatePoint(new Point3d(0.0, 0.0, 0.0));
            skt1_builder.SketchOrigin = origin_point;
            
            // 草图创建部分代码;
            Direction Zdir = workPart.Directions.CreateDirection(origin_point, new Vector3d(0.0, 0.0, 1.0));
            skt1_builder.AxisReference = Zdir;
            var sketch1 = (Sketch)skt1_builder.Commit();
            skt1_builder.Destroy();
            sketch1.Activate(Sketch.ViewReorient.True);

            Line line1 = workPart.Curves.CreateLine(point1, point2);
            Line line2 = workPart.Curves.CreateLine(point2, point3);
            Line line3 = workPart.Curves.CreateLine(point3, point4);
            Line line4 = workPart.Curves.CreateLine(point4, point1);

            Line[] Lines = {line1, line2, line3, line4};
            foreach (Line line in Lines)
            {
                sketch1.AddGeometry(line, Sketch.InferConstraintsOption.InferNoConstraints);
            }
            sketch1.Update();
            sketch1.Deactivate(Sketch.ViewReorient.False, Sketch.UpdateLevel.Model);  // 关闭草图

            // 数组使用 new 的初始化方法
            Section section1 = workPart.Sections.CreateSection();   // 使用默认的创建截面函数
            SelectionIntentRule[] rules1 = new NXOpen.SelectionIntentRule[1];
            
            // 将草图的线指定为截面线
            Feature[] features1 = new Feature[1];
            features1[0] = sketch1.Feature;         // 获取草图特征
            rules1[0] = workPart.ScRuleFactory.CreateRuleCurveFeatureChain(features1,line1,null,false,0.01);
            // 注意:CurveChainRule等等都是继承类，初始化此对象时, 

            // 注意: 这里直接使用 null 来指定 features (实际上是NXOpen.Features.Null)
            ExtrudeBuilder extrudeBuilder1 = workPart.Features.CreateExtrudeBuilder(null);
            extrudeBuilder1.Section = section1;
            // line1 是选中的部分, 而rules1指定了全选sketch中的内容
            section1.AddToSection(rules1, line1, null, null, new Point3d(0.0, 0.0, 0.0), Section.Mode.Create);
            
            // 指定拉伸方向, sense 指定向量的正向和反向, 并指定拉伸长度
            Direction dir2 = workPart.Directions.CreateDirection(sketch1, Sense.Forward, SmartObject.UpdateOption.WithinModeling);
            extrudeBuilder1.Direction = dir2;
            extrudeBuilder1.Limits.StartExtend.Value.RightHandSide = "0";
            extrudeBuilder1.Limits.EndExtend.Value.RightHandSide = "1";

            var cube_object = extrudeBuilder1.Commit();
            // extrudeBuilder1.Destroy();
        }
    }
}
```

```cs fold title:创建正方体的录制代码
// NX 12.0.0.27
// Journal created by Parrot on Mon Mar 18 17:55:37 2024 China Standard Time
//
using System;
using NXOpen;

public class NXJournal
{
  public static void Main(string[] args)
  {
    NXOpen.Session theSession = NXOpen.Session.GetSession();
    NXOpen.Part workPart = theSession.Parts.Work;
    NXOpen.Part displayPart = theSession.Parts.Display;
    // ----------------------------------------------
    //   Menu: Insert->Sketch...
    // ----------------------------------------------
    NXOpen.Session.UndoMarkId markId1;
    markId1 = theSession.SetUndoMark(NXOpen.Session.MarkVisibility.Visible, "Start");
    
    NXOpen.Sketch nullNXOpen_Sketch = null;
    NXOpen.SketchInPlaceBuilder sketchInPlaceBuilder1;
    sketchInPlaceBuilder1 = workPart.Sketches.CreateSketchInPlaceBuilder2(nullNXOpen_Sketch);
    
    NXOpen.Point3d origin1 = new NXOpen.Point3d(0.0, 0.0, 0.0);
    NXOpen.Vector3d normal1 = new NXOpen.Vector3d(0.0, 0.0, 1.0);
    NXOpen.Plane plane1;
    plane1 = workPart.Planes.CreatePlane(origin1, normal1, NXOpen.SmartObject.UpdateOption.WithinModeling);
    
    sketchInPlaceBuilder1.PlaneReference = plane1;
    
    NXOpen.Unit unit1 = (NXOpen.Unit)workPart.UnitCollection.FindObject("MilliMeter");
    NXOpen.Expression expression1;
    expression1 = workPart.Expressions.CreateSystemExpressionWithUnits("0", unit1);
    
    NXOpen.Expression expression2;
    expression2 = workPart.Expressions.CreateSystemExpressionWithUnits("0", unit1);
    
    NXOpen.SketchAlongPathBuilder sketchAlongPathBuilder1;
    sketchAlongPathBuilder1 = workPart.Sketches.CreateSketchAlongPathBuilder(nullNXOpen_Sketch);

    sketchInPlaceBuilder1.PlaneOption = NXOpen.Sketch.PlaneOption.ExistingPlane;    
    sketchInPlaceBuilder1.OriginOptionInfer = NXOpen.OriginMethod.WorkPartOrigin;
    
    sketchAlongPathBuilder1.PlaneLocation.Expression.RightHandSide = "0";
    
    theSession.SetUndoMarkName(markId1, "Create Sketch Dialog");
    
    plane1.SetMethod(NXOpen.PlaneTypes.MethodType.Coincident);
    
    plane1.SetMethod(NXOpen.PlaneTypes.MethodType.Coincident);
    
    NXOpen.NXObject[] geom1 = new NXOpen.NXObject[1];
    NXOpen.DatumPlane datumPlane1 = (NXOpen.DatumPlane)workPart.Datums.FindObject("DATUM_CSYS(0) XY plane");
    geom1[0] = datumPlane1;
    plane1.SetGeometry(geom1);
    
    plane1.SetAlternate(NXOpen.PlaneTypes.AlternateType.One);
    
    plane1.Evaluate();
    
    NXOpen.Expression expression3;
    expression3 = workPart.Expressions.CreateSystemExpressionWithUnits("0", unit1);
    
    NXOpen.Point3d origin2 = new NXOpen.Point3d(0.0, 0.0, 0.0);
    NXOpen.Vector3d vector1 = new NXOpen.Vector3d(1.0, 0.0, 0.0);
    NXOpen.Direction direction1;
    direction1 = workPart.Directions.CreateDirection(origin2, vector1, NXOpen.SmartObject.UpdateOption.WithinModeling);
    
    sketchInPlaceBuilder1.AxisReference = direction1;
    
    NXOpen.Expression expression4;
    expression4 = workPart.Expressions.CreateSystemExpressionWithUnits("0", unit1);
    
    NXOpen.Features.DatumCsys datumCsys1 = (NXOpen.Features.DatumCsys)workPart.Features.FindObject("DATUM_CSYS(0)");
    NXOpen.Point point1 = (NXOpen.Point)datumCsys1.FindObject("POINT 1");
    NXOpen.Xform nullNXOpen_Xform = null;
    NXOpen.Point point2;
    point2 = workPart.Points.CreatePoint(point1, nullNXOpen_Xform, NXOpen.SmartObject.UpdateOption.WithinModeling);
    
    NXOpen.NXObject nXObject1;
    NXOpen.Xform xform1;
    xform1 = workPart.Xforms.CreateExtractXform(point1, NXOpen.SmartObject.UpdateOption.WithinModeling, false, out nXObject1);
    
    NXOpen.Point point3 = (NXOpen.Point)nXObject1;
    NXOpen.Point point4;
    point4 = workPart.Points.CreatePoint(point3, nullNXOpen_Xform, NXOpen.SmartObject.UpdateOption.WithinModeling);
    
    sketchInPlaceBuilder1.SketchOrigin = point4;
    
    NXOpen.Session.UndoMarkId markId2;
    markId2 = theSession.SetUndoMark(NXOpen.Session.MarkVisibility.Invisible, "Create Sketch");
    
    theSession.DeleteUndoMark(markId2, null);
    
    NXOpen.Session.UndoMarkId markId3;
    markId3 = theSession.SetUndoMark(NXOpen.Session.MarkVisibility.Invisible, "Create Sketch");
    
    theSession.Preferences.Sketch.CreateInferredConstraints = true;
    
    theSession.Preferences.Sketch.ContinuousAutoDimensioning = true;
    
    theSession.Preferences.Sketch.DimensionLabel = NXOpen.Preferences.SketchPreferences.DimensionLabelType.Expression;
    
    theSession.Preferences.Sketch.TextSizeFixed = true;
    
    theSession.Preferences.Sketch.FixedTextSize = 3.0;
    
    theSession.Preferences.Sketch.DisplayParenthesesOnReferenceDimensions = true;
    
    theSession.Preferences.Sketch.DisplayReferenceGeometry = false;
    theSession.Preferences.Sketch.ConstraintSymbolSize = 3.0;
    theSession.Preferences.Sketch.DisplayObjectColor = false;
    
    theSession.Preferences.Sketch.DisplayObjectName = true;
    
    NXOpen.NXObject nXObject2;
    nXObject2 = sketchInPlaceBuilder1.Commit();
    NXOpen.Sketch sketch1 = (NXOpen.Sketch)nXObject2;
    NXOpen.Features.Feature feature1;
    feature1 = sketch1.Feature;
    
    NXOpen.Session.UndoMarkId markId4;
    markId4 = theSession.SetUndoMark(NXOpen.Session.MarkVisibility.Invisible, "update");
    
    int nErrs1;
    nErrs1 = theSession.UpdateManager.DoUpdate(markId4);
    sketch1.Activate(NXOpen.Sketch.ViewReorient.True);
    
    theSession.DeleteUndoMark(markId3, null);
    
    theSession.SetUndoMarkName(markId1, "Create Sketch");
    
    sketchInPlaceBuilder1.Destroy();
    
    sketchAlongPathBuilder1.Destroy();
    
    try
    {
      // Expression is still in use.
      workPart.Expressions.Delete(expression2);
    }
    catch (NXException ex)
    {
      ex.AssertErrorCode(1050029);
    }
    
    workPart.Expressions.Delete(expression4);
    
    try
    {
      // Expression is still in use.
      workPart.Expressions.Delete(expression1);
    }
    catch (NXException ex)
    {
      ex.AssertErrorCode(1050029);
    }
    
    workPart.Expressions.Delete(expression3);
    
    // ----------------------------------------------
    //   Menu: Insert->Sketch Curve->Rectangle...
    // ----------------------------------------------
    NXOpen.Session.UndoMarkId markId5;
    markId5 = theSession.SetUndoMark(NXOpen.Session.MarkVisibility.Invisible, "Profile short list");
    
    NXOpen.Session.UndoMarkId markId6;
    markId6 = theSession.SetUndoMark(NXOpen.Session.MarkVisibility.Invisible, "Create Rectangle");
    
    NXOpen.Expression expression5;
    expression5 = workPart.Expressions.CreateSystemExpression("1");
    
    NXOpen.Expression expression6;
    expression6 = workPart.Expressions.CreateSystemExpression("1");
    
    theSession.SetUndoMarkVisibility(markId6, "Create Rectangle", NXOpen.Session.MarkVisibility.Visible);
    
    // ----------------------------------------------
    // Creating rectangle using By 2 Points method 
    // ----------------------------------------------
    NXOpen.Point3d startPoint1 = new NXOpen.Point3d(0.0, 0.0, 0.0);
    NXOpen.Point3d endPoint1 = new NXOpen.Point3d(1.0, 0.0, 0.0);
    NXOpen.Line line1;
    line1 = workPart.Curves.CreateLine(startPoint1, endPoint1);
    
    NXOpen.Point3d startPoint2 = new NXOpen.Point3d(1.0, 0.0, 0.0);
    NXOpen.Point3d endPoint2 = new NXOpen.Point3d(1.0, 1.0, 0.0);
    NXOpen.Line line2;
    line2 = workPart.Curves.CreateLine(startPoint2, endPoint2);
    
    NXOpen.Point3d startPoint3 = new NXOpen.Point3d(1.0, 1.0, 0.0);
    NXOpen.Point3d endPoint3 = new NXOpen.Point3d(0.0, 1.0, 0.0);
    NXOpen.Line line3;
    line3 = workPart.Curves.CreateLine(startPoint3, endPoint3);
    
    NXOpen.Point3d startPoint4 = new NXOpen.Point3d(0.0, 1.0, 0.0);
    NXOpen.Point3d endPoint4 = new NXOpen.Point3d(0.0, 0.0, 0.0);
    NXOpen.Line line4;
    line4 = workPart.Curves.CreateLine(startPoint4, endPoint4);
    
    theSession.ActiveSketch.AddGeometry(line1, NXOpen.Sketch.InferConstraintsOption.InferNoConstraints);
    
    theSession.ActiveSketch.AddGeometry(line2, NXOpen.Sketch.InferConstraintsOption.InferNoConstraints);
    
    theSession.ActiveSketch.AddGeometry(line3, NXOpen.Sketch.InferConstraintsOption.InferNoConstraints);
    
    theSession.ActiveSketch.AddGeometry(line4, NXOpen.Sketch.InferConstraintsOption.InferNoConstraints);
    
    NXOpen.Sketch.ConstraintGeometry geom1_1 = new NXOpen.Sketch.ConstraintGeometry();
    geom1_1.Geometry = line1;
    geom1_1.PointType = NXOpen.Sketch.ConstraintPointType.EndVertex;
    geom1_1.SplineDefiningPointIndex = 0;
    NXOpen.Sketch.ConstraintGeometry geom2_1 = new NXOpen.Sketch.ConstraintGeometry();
    geom2_1.Geometry = line2;
    geom2_1.PointType = NXOpen.Sketch.ConstraintPointType.StartVertex;
    geom2_1.SplineDefiningPointIndex = 0;
    NXOpen.SketchGeometricConstraint sketchGeometricConstraint1;
    sketchGeometricConstraint1 = theSession.ActiveSketch.CreateCoincidentConstraint(geom1_1, geom2_1);
    
    NXOpen.Sketch.ConstraintGeometry geom1_2 = new NXOpen.Sketch.ConstraintGeometry();
    geom1_2.Geometry = line2;
    geom1_2.PointType = NXOpen.Sketch.ConstraintPointType.EndVertex;
    geom1_2.SplineDefiningPointIndex = 0;
    NXOpen.Sketch.ConstraintGeometry geom2_2 = new NXOpen.Sketch.ConstraintGeometry();
    geom2_2.Geometry = line3;
    geom2_2.PointType = NXOpen.Sketch.ConstraintPointType.StartVertex;
    geom2_2.SplineDefiningPointIndex = 0;
    NXOpen.SketchGeometricConstraint sketchGeometricConstraint2;
    sketchGeometricConstraint2 = theSession.ActiveSketch.CreateCoincidentConstraint(geom1_2, geom2_2);
    
    NXOpen.Sketch.ConstraintGeometry geom1_3 = new NXOpen.Sketch.ConstraintGeometry();
    geom1_3.Geometry = line3;
    geom1_3.PointType = NXOpen.Sketch.ConstraintPointType.EndVertex;
    geom1_3.SplineDefiningPointIndex = 0;
    NXOpen.Sketch.ConstraintGeometry geom2_3 = new NXOpen.Sketch.ConstraintGeometry();
    geom2_3.Geometry = line4;
    geom2_3.PointType = NXOpen.Sketch.ConstraintPointType.StartVertex;
    geom2_3.SplineDefiningPointIndex = 0;
    NXOpen.SketchGeometricConstraint sketchGeometricConstraint3;
    sketchGeometricConstraint3 = theSession.ActiveSketch.CreateCoincidentConstraint(geom1_3, geom2_3);
    
    NXOpen.Sketch.ConstraintGeometry geom1_4 = new NXOpen.Sketch.ConstraintGeometry();
    geom1_4.Geometry = line4;
    geom1_4.PointType = NXOpen.Sketch.ConstraintPointType.EndVertex;
    geom1_4.SplineDefiningPointIndex = 0;
    NXOpen.Sketch.ConstraintGeometry geom2_4 = new NXOpen.Sketch.ConstraintGeometry();
    geom2_4.Geometry = line1;
    geom2_4.PointType = NXOpen.Sketch.ConstraintPointType.StartVertex;
    geom2_4.SplineDefiningPointIndex = 0;
    NXOpen.SketchGeometricConstraint sketchGeometricConstraint4;
    sketchGeometricConstraint4 = theSession.ActiveSketch.CreateCoincidentConstraint(geom1_4, geom2_4);
    
    NXOpen.Sketch.ConstraintGeometry geom2 = new NXOpen.Sketch.ConstraintGeometry();
    geom2.Geometry = line1;
    geom2.PointType = NXOpen.Sketch.ConstraintPointType.None;
    geom2.SplineDefiningPointIndex = 0;
    NXOpen.SketchGeometricConstraint sketchGeometricConstraint5;
    sketchGeometricConstraint5 = theSession.ActiveSketch.CreateHorizontalConstraint(geom2);
    
    NXOpen.Sketch.ConstraintGeometry conGeom1_1 = new NXOpen.Sketch.ConstraintGeometry();
    conGeom1_1.Geometry = line1;
    conGeom1_1.PointType = NXOpen.Sketch.ConstraintPointType.None;
    conGeom1_1.SplineDefiningPointIndex = 0;
    NXOpen.Sketch.ConstraintGeometry conGeom2_1 = new NXOpen.Sketch.ConstraintGeometry();
    conGeom2_1.Geometry = line2;
    conGeom2_1.PointType = NXOpen.Sketch.ConstraintPointType.None;
    conGeom2_1.SplineDefiningPointIndex = 0;
    NXOpen.SketchGeometricConstraint sketchGeometricConstraint6;
    sketchGeometricConstraint6 = theSession.ActiveSketch.CreatePerpendicularConstraint(conGeom1_1, conGeom2_1);
    
    NXOpen.Sketch.ConstraintGeometry conGeom1_2 = new NXOpen.Sketch.ConstraintGeometry();
    conGeom1_2.Geometry = line2;
    conGeom1_2.PointType = NXOpen.Sketch.ConstraintPointType.None;
    conGeom1_2.SplineDefiningPointIndex = 0;
    NXOpen.Sketch.ConstraintGeometry conGeom2_2 = new NXOpen.Sketch.ConstraintGeometry();
    conGeom2_2.Geometry = line3;
    conGeom2_2.PointType = NXOpen.Sketch.ConstraintPointType.None;
    conGeom2_2.SplineDefiningPointIndex = 0;
    NXOpen.SketchGeometricConstraint sketchGeometricConstraint7;
    sketchGeometricConstraint7 = theSession.ActiveSketch.CreatePerpendicularConstraint(conGeom1_2, conGeom2_2);
    
    NXOpen.Sketch.ConstraintGeometry conGeom1_3 = new NXOpen.Sketch.ConstraintGeometry();
    conGeom1_3.Geometry = line3;
    conGeom1_3.PointType = NXOpen.Sketch.ConstraintPointType.None;
    conGeom1_3.SplineDefiningPointIndex = 0;
    NXOpen.Sketch.ConstraintGeometry conGeom2_3 = new NXOpen.Sketch.ConstraintGeometry();
    conGeom2_3.Geometry = line4;
    conGeom2_3.PointType = NXOpen.Sketch.ConstraintPointType.None;
    conGeom2_3.SplineDefiningPointIndex = 0;
    NXOpen.SketchGeometricConstraint sketchGeometricConstraint8;
    sketchGeometricConstraint8 = theSession.ActiveSketch.CreatePerpendicularConstraint(conGeom1_3, conGeom2_3);
    
    NXOpen.Sketch.ConstraintGeometry conGeom1_4 = new NXOpen.Sketch.ConstraintGeometry();
    conGeom1_4.Geometry = line4;
    conGeom1_4.PointType = NXOpen.Sketch.ConstraintPointType.None;
    conGeom1_4.SplineDefiningPointIndex = 0;
    NXOpen.Sketch.ConstraintGeometry conGeom2_4 = new NXOpen.Sketch.ConstraintGeometry();
    conGeom2_4.Geometry = line1;
    conGeom2_4.PointType = NXOpen.Sketch.ConstraintPointType.None;
    conGeom2_4.SplineDefiningPointIndex = 0;
    NXOpen.SketchGeometricConstraint sketchGeometricConstraint9;
    sketchGeometricConstraint9 = theSession.ActiveSketch.CreatePerpendicularConstraint(conGeom1_4, conGeom2_4);
    
    NXOpen.Sketch.ConstraintGeometry geom1_5 = new NXOpen.Sketch.ConstraintGeometry();
    geom1_5.Geometry = line1;
    geom1_5.PointType = NXOpen.Sketch.ConstraintPointType.StartVertex;
    geom1_5.SplineDefiningPointIndex = 0;
    NXOpen.Sketch.ConstraintGeometry geom2_5 = new NXOpen.Sketch.ConstraintGeometry();
    NXOpen.Features.DatumCsys datumCsys2 = (NXOpen.Features.DatumCsys)workPart.Features.FindObject("SKETCH(1:1B)");
    NXOpen.Point point5 = (NXOpen.Point)datumCsys2.FindObject("POINT 1");
    geom2_5.Geometry = point5;
    geom2_5.PointType = NXOpen.Sketch.ConstraintPointType.None;
    geom2_5.SplineDefiningPointIndex = 0;
    NXOpen.SketchGeometricConstraint sketchGeometricConstraint10;
    sketchGeometricConstraint10 = theSession.ActiveSketch.CreateCoincidentConstraint(geom1_5, geom2_5);
    
    NXOpen.Sketch.DimensionGeometry dimObject1_1 = new NXOpen.Sketch.DimensionGeometry();
    dimObject1_1.Geometry = line1;
    dimObject1_1.AssocType = NXOpen.Sketch.AssocType.StartPoint;
    dimObject1_1.AssocValue = 0;
    dimObject1_1.HelpPoint.X = 0.0;
    dimObject1_1.HelpPoint.Y = 0.0;
    dimObject1_1.HelpPoint.Z = 0.0;
    NXOpen.NXObject nullNXOpen_NXObject = null;
    dimObject1_1.View = nullNXOpen_NXObject;
    NXOpen.Sketch.DimensionGeometry dimObject2_1 = new NXOpen.Sketch.DimensionGeometry();
    dimObject2_1.Geometry = line1;
    dimObject2_1.AssocType = NXOpen.Sketch.AssocType.EndPoint;
    dimObject2_1.AssocValue = 0;
    dimObject2_1.HelpPoint.X = 0.0;
    dimObject2_1.HelpPoint.Y = 0.0;
    dimObject2_1.HelpPoint.Z = 0.0;
    dimObject2_1.View = nullNXOpen_NXObject;
    NXOpen.Point3d dimOrigin1 = new NXOpen.Point3d(0.5, -0.082151806997551174, 0.0);
    NXOpen.SketchDimensionalConstraint sketchDimensionalConstraint1;
    sketchDimensionalConstraint1 = theSession.ActiveSketch.CreateDimension(NXOpen.Sketch.ConstraintType.ParallelDim, dimObject1_1, dimObject2_1, dimOrigin1, expression5, NXOpen.Sketch.DimensionOption.CreateAsDriving);
    
    NXOpen.SketchHelpedDimensionalConstraint sketchHelpedDimensionalConstraint1 = (NXOpen.SketchHelpedDimensionalConstraint)sketchDimensionalConstraint1;
    NXOpen.Annotations.Dimension dimension1;
    dimension1 = sketchHelpedDimensionalConstraint1.AssociatedDimension;
    
    NXOpen.Sketch.DimensionGeometry dimObject1_2 = new NXOpen.Sketch.DimensionGeometry();
    dimObject1_2.Geometry = line2;
    dimObject1_2.AssocType = NXOpen.Sketch.AssocType.StartPoint;
    dimObject1_2.AssocValue = 0;
    dimObject1_2.HelpPoint.X = 0.0;
    dimObject1_2.HelpPoint.Y = 0.0;
    dimObject1_2.HelpPoint.Z = 0.0;
    dimObject1_2.View = nullNXOpen_NXObject;
    NXOpen.Sketch.DimensionGeometry dimObject2_2 = new NXOpen.Sketch.DimensionGeometry();
    dimObject2_2.Geometry = line2;
    dimObject2_2.AssocType = NXOpen.Sketch.AssocType.EndPoint;
    dimObject2_2.AssocValue = 0;
    dimObject2_2.HelpPoint.X = 0.0;
    dimObject2_2.HelpPoint.Y = 0.0;
    dimObject2_2.HelpPoint.Z = 0.0;
    dimObject2_2.View = nullNXOpen_NXObject;
    NXOpen.Point3d dimOrigin2 = new NXOpen.Point3d(1.0821518069975511, 0.5, 0.0);
    NXOpen.SketchDimensionalConstraint sketchDimensionalConstraint2;
    sketchDimensionalConstraint2 = theSession.ActiveSketch.CreateDimension(NXOpen.Sketch.ConstraintType.ParallelDim, dimObject1_2, dimObject2_2, dimOrigin2, expression6, NXOpen.Sketch.DimensionOption.CreateAsDriving);
     
    NXOpen.SketchHelpedDimensionalConstraint sketchHelpedDimensionalConstraint2 = (NXOpen.SketchHelpedDimensionalConstraint)sketchDimensionalConstraint2;
    NXOpen.Annotations.Dimension dimension2;
    dimension2 = sketchHelpedDimensionalConstraint2.AssociatedDimension;
    
    theSession.Preferences.Sketch.AutoDimensionsToArcCenter = false;
    
    theSession.ActiveSketch.Update();
    
    theSession.Preferences.Sketch.AutoDimensionsToArcCenter = true;
    
    NXOpen.SmartObject[] geoms1 = new NXOpen.SmartObject[4];
    geoms1[0] = line1;
    geoms1[1] = line2;
    geoms1[2] = line3;
    geoms1[3] = line4;
    theSession.ActiveSketch.UpdateConstraintDisplay(geoms1);

    NXOpen.SmartObject[] geoms2 = new NXOpen.SmartObject[4];
    geoms2[0] = line1;
    geoms2[1] = line2;
    geoms2[2] = line3;
    geoms2[3] = line4;
    theSession.ActiveSketch.UpdateDimensionDisplay(geoms2);

    // ----------------------------------------------
    //   Menu: File->Finish Sketch
    // ----------------------------------------------
    NXOpen.Sketch sketch2;
    sketch2 = theSession.ActiveSketch;
    
    NXOpen.Session.UndoMarkId markId7;
    markId7 = theSession.SetUndoMark(NXOpen.Session.MarkVisibility.Invisible, "Deactivate Sketch");
    
    theSession.ActiveSketch.Deactivate(NXOpen.Sketch.ViewReorient.True, NXOpen.Sketch.UpdateLevel.Model);

	
    NXOpen.Matrix3x3 rotMatrix1 = new NXOpen.Matrix3x3();
    rotMatrix1.Xx = 0.99861390282802087;
    rotMatrix1.Xy = -0.045285030388745019;
    rotMatrix1.Xz = -0.026824226014539342;
    rotMatrix1.Yx = 0.052276604884783341;
    rotMatrix1.Yy = 0.79412973662378383;
    rotMatrix1.Yz = 0.60549576215821843;
    rotMatrix1.Zx = -0.0061179784495281903;
    rotMatrix1.Zy = -0.60605876565934769;
    rotMatrix1.Zz = 0.79539634328249376;
    NXOpen.Point3d translation1 = new NXOpen.Point3d(-0.74434674404372525, -0.55060910724208689, 0.26049559182300974);
    workPart.ModelingViews.WorkView.SetRotationTranslationScale(rotMatrix1, translation1, 109.55328104065048);
    
    // ----------------------------------------------
    //   Menu: Insert->Design Feature->Extrude...
    // ----------------------------------------------
    NXOpen.Session.UndoMarkId markId8;
    markId8 = theSession.SetUndoMark(NXOpen.Session.MarkVisibility.Visible, "Start");
    
    NXOpen.Features.Feature nullNXOpen_Features_Feature = null;
    NXOpen.Features.ExtrudeBuilder extrudeBuilder1;
    extrudeBuilder1 = workPart.Features.CreateExtrudeBuilder(nullNXOpen_Features_Feature);
    
    NXOpen.Section section1;
    section1 = workPart.Sections.CreateSection(0.0094999999999999998, 0.01, 0.5);
    extrudeBuilder1.Section = section1;
    extrudeBuilder1.AllowSelfIntersectingSection(true);
    
    NXOpen.Unit unit2;
    unit2 = extrudeBuilder1.Draft.FrontDraftAngle.Units;
    
    NXOpen.Expression expression7;
    expression7 = workPart.Expressions.CreateSystemExpressionWithUnits("2.00", unit2);
    
    extrudeBuilder1.DistanceTolerance = 0.01;
    
    extrudeBuilder1.BooleanOperation.Type = NXOpen.GeometricUtilities.BooleanOperation.BooleanType.Create;
    
    NXOpen.Body[] targetBodies1 = new NXOpen.Body[1];
    NXOpen.Body nullNXOpen_Body = null;
    targetBodies1[0] = nullNXOpen_Body;
    extrudeBuilder1.BooleanOperation.SetTargetBodies(targetBodies1);
    
    extrudeBuilder1.Limits.StartExtend.Value.RightHandSide = "0";
    
    extrudeBuilder1.Limits.EndExtend.Value.RightHandSide = "1";
    
    extrudeBuilder1.Draft.FrontDraftAngle.RightHandSide = "2";
    
    extrudeBuilder1.Draft.BackDraftAngle.RightHandSide = "2";
    
    extrudeBuilder1.Offset.StartOffset.RightHandSide = "0";
    
    extrudeBuilder1.Offset.EndOffset.RightHandSide = "5";
    
    NXOpen.GeometricUtilities.SmartVolumeProfileBuilder smartVolumeProfileBuilder1;
    smartVolumeProfileBuilder1 = extrudeBuilder1.SmartVolumeProfile;
    
    smartVolumeProfileBuilder1.OpenProfileSmartVolumeOption = false;
    
    smartVolumeProfileBuilder1.CloseProfileRule = NXOpen.GeometricUtilities.SmartVolumeProfileBuilder.CloseProfileRuleType.Fci;
    
    theSession.SetUndoMarkName(markId8, "Extrude Dialog");
    
    section1.DistanceTolerance = 0.01;
    
    section1.ChainingTolerance = 0.0094999999999999998;
    
    section1.SetAllowedEntityTypes(NXOpen.Section.AllowTypes.OnlyCurves);
    
    NXOpen.Session.UndoMarkId markId9;
    markId9 = theSession.SetUndoMark(NXOpen.Session.MarkVisibility.Invisible, "section mark");
    
    NXOpen.Session.UndoMarkId markId10;
    markId10 = theSession.SetUndoMark(NXOpen.Session.MarkVisibility.Invisible, null);
    
    NXOpen.Features.Feature[] features1 = new NXOpen.Features.Feature[1];
    NXOpen.Features.SketchFeature sketchFeature1 =(NXOpen.Features.SketchFeature)feature1;
    features1[0] = sketchFeature1;
    NXOpen.Curve nullNXOpen_Curve = null;
    NXOpen.CurveFeatureChainRule curveFeatureChainRule1;
    curveFeatureChainRule1 = workPart.ScRuleFactory.CreateRuleCurveFeatureChain(features1, line3, nullNXOpen_Curve, false, 0.0094999999999999998);
    
    section1.AllowSelfIntersection(true);
    
    NXOpen.SelectionIntentRule[] rules1 = new NXOpen.SelectionIntentRule[1];
    rules1[0] = curveFeatureChainRule1;
    NXOpen.Point3d helpPoint1 = new NXOpen.Point3d(0.63676099233125261, 1.000000000000002, -6.6613381477509392e-16);
    section1.AddToSection(rules1, line3, nullNXOpen_NXObject, nullNXOpen_NXObject, helpPoint1, NXOpen.Section.Mode.Create, false);
    
    theSession.DeleteUndoMark(markId10, null);
    
    NXOpen.Direction direction2;
    direction2 = workPart.Directions.CreateDirection(sketch2, NXOpen.Sense.Forward, NXOpen.SmartObject.UpdateOption.WithinModeling);
     
    extrudeBuilder1.Direction = direction2;
    
    NXOpen.Expression expression8;
    expression8 = workPart.Expressions.CreateSystemExpressionWithUnits("0", unit1);
    
    theSession.DeleteUndoMark(markId9, null);
    
    NXOpen.Matrix3x3 rotMatrix2 = new NXOpen.Matrix3x3();
    rotMatrix2.Xx = 0.99422572787855179;
    rotMatrix2.Xy = -0.10730667047521569;
    rotMatrix2.Xz = 0.00069317810687495899;
    rotMatrix2.Yx = 0.042629257230552851;
    rotMatrix2.Yy = 0.40088334560511718;
    rotMatrix2.Yz = 0.91513676007710643;
    rotMatrix2.Zx = -0.098478162311934458;
    rotMatrix2.Zy = -0.90982296172825561;
    rotMatrix2.Zz = 0.40314293973687937;
    NXOpen.Point3d translation2 = new NXOpen.Point3d(-0.72881744402228932, -0.53018802835812928, 0.64084334694339773);
    workPart.ModelingViews.WorkView.SetRotationTranslationScale(rotMatrix2, translation2, 109.55328104065048);
    
    NXOpen.Session.UndoMarkId markId11;
    markId11 = theSession.SetUndoMark(NXOpen.Session.MarkVisibility.Invisible, "Extrude");
    
    extrudeBuilder1.ParentFeatureInternal = false;
    
    NXOpen.Features.Feature feature2;
    feature2 = extrudeBuilder1.CommitFeature();
    
    theSession.DeleteUndoMark(markId11, null);
    
    theSession.SetUndoMarkName(markId8, "Extrude");
    
    NXOpen.Expression expression9 = extrudeBuilder1.Limits.StartExtend.Value;
    NXOpen.Expression expression10 = extrudeBuilder1.Limits.EndExtend.Value;
    extrudeBuilder1.Destroy();
    
    workPart.Expressions.Delete(expression7);
    
    workPart.Expressions.Delete(expression8);
    
    NXOpen.Session.UndoMarkId markId12;
    markId12 = theSession.SetUndoMark(NXOpen.Session.MarkVisibility.Visible, "Start");
    
    NXOpen.Features.ExtrudeBuilder extrudeBuilder2;
    extrudeBuilder2 = workPart.Features.CreateExtrudeBuilder(nullNXOpen_Features_Feature);
    
    NXOpen.Section section2;
    section2 = workPart.Sections.CreateSection(0.0094999999999999998, 0.01, 0.5);
    
    extrudeBuilder2.Section = section2;
    
    extrudeBuilder2.AllowSelfIntersectingSection(true);
    
    NXOpen.Expression expression11;
    expression11 = workPart.Expressions.CreateSystemExpressionWithUnits("2.00", unit2);
    
    extrudeBuilder2.DistanceTolerance = 0.01;
    
    extrudeBuilder2.BooleanOperation.Type = NXOpen.GeometricUtilities.BooleanOperation.BooleanType.Create;
    
    NXOpen.Body[] targetBodies2 = new NXOpen.Body[1];
    targetBodies2[0] = nullNXOpen_Body;
    extrudeBuilder2.BooleanOperation.SetTargetBodies(targetBodies2);
    
    extrudeBuilder2.Limits.StartExtend.Value.RightHandSide = "0";
    
    extrudeBuilder2.Limits.EndExtend.Value.RightHandSide = "1";
    
    extrudeBuilder2.BooleanOperation.Type = NXOpen.GeometricUtilities.BooleanOperation.BooleanType.Create;
    
    NXOpen.Body[] targetBodies3 = new NXOpen.Body[1];
    targetBodies3[0] = nullNXOpen_Body;
    extrudeBuilder2.BooleanOperation.SetTargetBodies(targetBodies3);
    
    extrudeBuilder2.Draft.FrontDraftAngle.RightHandSide = "2";
    
    extrudeBuilder2.Draft.BackDraftAngle.RightHandSide = "2";
    
    extrudeBuilder2.Offset.StartOffset.RightHandSide = "0";
    
    extrudeBuilder2.Offset.EndOffset.RightHandSide = "5";
    
    NXOpen.GeometricUtilities.SmartVolumeProfileBuilder smartVolumeProfileBuilder2;
    smartVolumeProfileBuilder2 = extrudeBuilder2.SmartVolumeProfile;
    
    smartVolumeProfileBuilder2.OpenProfileSmartVolumeOption = false;
    
    smartVolumeProfileBuilder2.CloseProfileRule = NXOpen.GeometricUtilities.SmartVolumeProfileBuilder.CloseProfileRuleType.Fci;
    
    theSession.SetUndoMarkName(markId12, "Extrude Dialog");
    
    section2.DistanceTolerance = 0.01;
    
    section2.ChainingTolerance = 0.0094999999999999998;
    
    // ----------------------------------------------
    //   Dialog Begin Extrude
    // ----------------------------------------------
    section2.SetAllowedEntityTypes(NXOpen.Section.AllowTypes.OnlyCurves);
    
    extrudeBuilder2.Destroy();
    
    section2.Destroy();
    
    workPart.Expressions.Delete(expression11);
    
    theSession.UndoToMark(markId12, null);
    
    theSession.DeleteUndoMark(markId12, null);
    
    NXOpen.Session.UndoMarkId markId13;
    markId13 = theSession.SetUndoMark(NXOpen.Session.MarkVisibility.Visible, "Hide");
    
    NXOpen.DisplayableObject[] objects1 = new NXOpen.DisplayableObject[1];
    objects1[0] = sketch2;
    theSession.DisplayManager.BlankObjects(objects1);
    
    workPart.ModelingViews.WorkView.FitAfterShowOrHide(NXOpen.View.ShowOrHideType.HideOnly);
    
    // ----------------------------------------------
    //   Menu: File->Save
    // ----------------------------------------------
    NXOpen.PartSaveStatus partSaveStatus1;
    partSaveStatus1 = workPart.Save(NXOpen.BasePart.SaveComponents.True, NXOpen.BasePart.CloseAfterSave.False);
    
    partSaveStatus1.Dispose();
    // ----------------------------------------------
    //   Menu: Tools->Journal->Stop Recording
    // ----------------------------------------------
    
  }
  public static int GetUnloadOption(string dummy) { return (int)NXOpen.Session.LibraryUnloadOption.Immediately; }
```
### (2) 撤销标签,  标签寻址和删除特征
首先，删除特征等需要了解 UndoMarkID 的用法, <b><mark style="background: transparent; color: blue">UndoMarkID 实际上是 "撤销标志位"的意思, 一般在 Session.UpdateManager.DoUpdate 方法中都要调用来便于撤销操作</mark></b>;
```cs title:设置UndoMarkID实际上只需要一句代码
var markDelete = session.SetUndoMark(Session.MarkVisibility.Invisible, "delete"); 
// 其中Visible 设置是否用户是可见的， 即是否允许用户的撤销操作
```

```cs title:删除一个方块的代码
TaggedObject[] obj1 = new TaggedObject[1];
obj1[0] = (NXOpen.Features.Extrude) cube1;

session.UpdateManager.AddObjectsToDeleteList(obj1);
// 创建标志点, 可以使用 UndoToMarkWithStatus回滚到之前的状态; -> 其中Visible 设置对用户可见
var markDelete = session.SetUndoMark(Session.MarkVisibility.Visible, "Delete");
session.UpdateManager.DoUpdate(markDelete);
session.DeleteUndoMark(markDelete,"Delete");  // 删除UndoMark, 第一个参数是对应的变量，第二个给定字符串, 一般是标记点
```

如果是想为一个部分设置名称，可以调用SetName方法, 之后可以通过在Session 的WorkPart中遍历获取对应的方法; <mark style="background: transparent; color: red">以下代码演示了设置名称， 和遍历草图寻找名称然后进行删除操作</mark>;

> [!caution] 注意
> 对于草图， 也可以直接使用workPart.Sketches.FindObject 会导致找不到对象, 

```cs
sketch1.SetName("TestSketch");

foreach (Sketch sketch in session.Parts.Work.Sketches)
{
	if (sketch.Name == "TESTSKETCH")
	{
		// 删除名字是TESTSKETCH的草图
		Delete_object(session, sketch);
	}
}
```

### (3) 创建平面的方法

```cs title:一般平面创建方法 
workPart.Planes.CreatePlane(new Point3d(0.0, 0.0, 0.0), new Vector3d(1.0, 0.0, 0.0), SmartObject.UpdateOption.WithinModeling);
// 这个一般是正确的， 但是如果平面浮空， 则创建草图时会有Internal Error, 因此可以使用参考平面代替
```

参考平面是通过先设定一系列值， 然后最后使用 Evaluate 进行创建的。
```cs title:参考平面创建
// dataum plane creation
DatumPlaneBuilder datumPlaneBuilder1;
datumPlaneBuilder1 = workPart.Features.CreateDatumPlaneBuilder(null);

Plane plane2 = datumPlaneBuilder1.GetPlane();
plane2.SetMethod(PlaneTypes.MethodType.Distance);
NXObject[] geom1 = new NXObject[1] { coor_ref.Plane_ref.XZplane };  //设置参考对象(随便一个平面)
plane2.SetGeometry(geom1);   // 赋值到Geometry属性中; 
plane2.SetFlip(false);
plane2.SetReverseSide(false);
plane2.Expression.RightHandSide = TJParameter.flangeThickness.ToString();
plane2.SetAlternate(PlaneTypes.AlternateType.One);  // 一般直接加上即可， 不管太多
plane2.Evaluate();  // evalue the plane (replace the plane)


// create points on reference plane 2 -> 在参考平面上创建草图
var sketchbuilder2 = workPart.Sketches.CreateSketchInPlaceBuilder2(null);  // null for brand new sketch
sketchbuilder2.SketchOrigin = coor_ref.origin;
sketchbuilder2.AxisReference = coor_ref.Direction_ref.x_Direction;
sketchbuilder2.PlaneReference = plane2;
Sketch sketch2 = (Sketch)sketchbuilder2.Commit();
sketchbuilder2.Destroy();
```

### (4) 在平面上钻孔的代码
可以通过
```cs
NXOpen.Session.BeginTaskEnvironment() 
```
来进入一个子工作环境， 例如添加孔时，绘制草图等等

我们实际指定孔时,  最终将点添加到孔的操作调用的函数是
```cs
HolePackageBuilder holebuilder1 =  workPart.Features.CreateHolePackageBuilder(null); // 创建孔

holePackageBuilder3.HolePosition.AddToSection(rules, null, null, null, helpPoint, NXOpen.Section.Mode.Create);
```
通过HolePosition设置多个孔的位置, 实际上返回的是一个 Section 对象, 而可以通过AddToSection向其中添加截面规则; 
注意设置Body对象不能直接强制类型转换， 否则会出现 `Unable to cast object of type 'NXOpen.Features.Extrude' to type 'NXOpen.Body'.` 实际上， 应该使用 Extrude 类型的GetBodies方法;

钻孔指定直径和深度时， **必须事先指定钻孔类型，然后再指定对应类型孔的高度和直径** 
```cs fold title:孔组的基本添加操作代码(首先需要三个点)
// --------- Create Hole Features ----------------- 
var markID4 = theSession.SetUndoMark(Session.MarkVisibility.Visible, "Create Holes");

HolePackageBuilder holebuilder1 =  workPart.Features.CreateHolePackageBuilder(null); // new hole feature 

holebuilder1.StartHoleData.BooleanOperation.SetTargetBodies(new Body[]{ null });
holebuilder1.MiddleHoleData.BooleanOperation.SetTargetBodies(new Body[] { null });
// Boolean Type is from GeometricUtilitiess (Optional)
holebuilder1.StartHoleData.BooleanOperation.Type = BooleanOperation.BooleanType.Subtract;

Body[] body1 = new Body[] { null };
holebuilder1.BooleanOperation.SetTargetBodies(body1);
// 三个部分, 这三个部分可以不加(都是默认)
holebuilder1.StartHoleData.BooleanOperation.SetTargetBodies(new Body[] { null });
holebuilder1.MiddleHoleData.BooleanOperation.SetTargetBodies(new Body[] { null });
holebuilder1.EndHoleData.BooleanOperation.SetTargetBodies(new Body[] { null });
holebuilder1.HolePosition.SetAllowedEntityTypes(NXOpen.Section.AllowTypes.OnlyPoints);
// 设置 Tolerance 部分
holebuilder1.Tolerance = 0.01;
holebuilder1.HolePosition.DistanceTolerance = 0.01;
holebuilder1.HolePosition.ChainingTolerance = 0.0096;

/* 设置Boolean Operation 的 TargetBody 属性才是设置对应的布尔对象 */
Body[] flange1_body = flange1.GetBodies();   // 直接从flange1 获取bodies对象(注意必须是Extrude类型)
holebuilder1.BooleanOperation.SetTargetBodies(flange1_body);
// 设置孔的直径和高度
holebuilder1.Type = HolePackageBuilder.Types.GeneralHole;  // 构造类型
holebuilder1.GeneralCounterboreDiameter.RightHandSide = TJParameter.flangeThickness.ToString();
holebuilder1.GeneralCounterboreHoleDepth.RightHandSide = TJParameter.flangeHoleDiameter.ToString();
// 用CurveDumbRule将所有的点添加到点集中;
Point[] points1 = new Point[] { workPart.Points.CreatePoint(point5), 
								workPart.Points.CreatePoint(point6),
								workPart.Points.CreatePoint(point7)};
CurveDumbRule[] rules2 = new CurveDumbRule[] { workPart.ScRuleFactory.CreateRuleCurveDumbFromPoints(points1) };
holebuilder1.HolePosition.AddToSection(rules2, null, null, null, new Point3d(0.0,0.0,0.0), Section.Mode.Create);

var holepackage1 = (HolePackage)holebuilder1.Commit();
holepackage1.SetName("Flange Holes");
holebuilder1.Destroy();
```

### (3) 设置对象的隐藏和显示
方法是创建一个DisplayableObject,  
```cs
// ------------- Hide The Sketches ------------- 
theSession.SetUndoMark(Session.MarkVisibility.Visible, "Hide Sketch");
DisplayableObject[] objects1 = new DisplayableObject[2];
objects1[0] = sketch1;
objects1[1] = sketch2;
theSession.DisplayManager.BlankObjects(objects1);  // 取消其中这些的显示
// theSession.DisplayManager.ShowObjects -> 显示对应的对象
```
